[project]
name = "relaxation-labelling"
version = "0.1.0"
description = "Using relxation for pseudo-labelling for homophonic ciphertexts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "nltk>=3.9.2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.13.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["test"]
addopts = "-v --tb=short --cov=src --cov-report=term-missing"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
exclude = ["venv", ".venv", "__pycache__", "build", "dist", ".eggs", "*.egg", ".mypy_cache", ".pytest_cache"]
select = ["E", "F", "W", "C90", "B", "B9", "ANN", "COM", "D", "ERA", "ISC", "N", "Q000", "S", "SIM", "TID251", "UP", "YTT", "T"]
ignore = [
	"W191",  # indentation contains tabs
	"S311",  # Standard pseudo-random generators are not suitable for security/cryptographic purposes
	"D206",  # Docstring should be indented with spaces equal to the surrounding code
	"D100",  # Missing docstring in public module
	"D203",  # incorrect-blank-line-before-class
	"D213",  # multi-line-summary-second-line
	"UP035", # Import from `collections.abc`instead: ...
	"ANN401",# Dynamically typed expressions (typing.Any) are disallowed 
]

[tool.ruff.lint.per-file-ignores]
"test/**/*.py" = [
    "S101",    # Use of assert detected
    "D",       # All docstring rules
    "ANN",     # All type annotation rules
	"E501",   # Line too long
	"COM812",  # Missing trailing comma in a list or dict
	"ERA001", # Found commented-out code
]
[tool.ruff.format]
indent-style = "tab"

[tool.uv.sources]
parameter-validator = { git = "https://github.com/jatewo/parameter-validator.git" }
